### ISSUE TITLE
No sound and SimpleAgenda crashes

### ISSUE THREAD

**Issue by cneira** [onflapp/gs-desktop#1]
Great work!!!
I have been waiting for something like this for ages!, 
I just tested on an old laptop with debian 11 and it works great!

The following is the only thing I needed to add to my .xsessionrc to make sound and SimpleAgenda work, is this:

```sh
neirac@GNUNeXT:~$ cat .xsessionrc
synclient TapButton1=1
pulseaudio --start
start-pulseaudio-x11
dbus-launch --exit-with-session ~/.xsessionrc
exec /System/bin/startgsde
```

**Comment by onflapp** [comment]
As long as you include all dependencies, no further setup is necessary. Both pulseaudio server and dbus should launch on demand. (I just tested it with clean Debian11).

Maybe you have custom setup (e.g. not using pulseaudio by default?)

**Comment by cneira** [comment]
I just tested in a new Debian 11 installation, I'll close this as is not a show stopper.

**Comment by onflapp** [comment]
> I just tested in a new Debian 11 installation, I'll close this as is not a show stopper.

I'll make Debian 11 hard requirement for now.
My aim is to create dedicated distro one day. With documentation, example, everything in one place.

**Comment by cneira** [comment]
> > I just tested in a new Debian 11 installation, I'll close this as is not a show stopper.
> 
> I'll make Debian 11 hard requirement for now. My aim is to create dedicated distro one day. With documentation, for example, everything is in one place.

That's awesome! I want a GNUStep-based distro that could be used daily, I'm using your work as a daily driver, and trying to find things that don't work well, and I'll report back hopefully with some patches.
Great work in compiling this!!
