### ISSUE TITLE
Retina Display

### ISSUE THREAD

**Issue by austintatiousness** [onflapp/gs-desktop#10]
I would love for there to be a setting in Display Preferences that can set the x2 scaling for retina displays. I know it is a little buggy, but the change would be greatly appreciated.

**Comment by onflapp** [comment]
I evaluated different options how to run GSDE on the retina and I found GNUstep scaling so broken that I've decided not to exposes in via Display Preferences.

You can still do `defaults write NSGlobalDomain GSScaleFactor 1.5` of course.

The only reasonable solution I see right now is to use xrandr and scale the whole display.
Although even this seems to be broken on some hardware I've tested.
