### ISSUE TITLE
Please add a wiki : users could help document things

### ISSUE THREAD

**Issue by zeroheure** [onflapp/gs-desktop#11]
Title says all : with a wiki, I could add some docs about ... applications, install/updates, wrappers, steptalk, etc.

**Comment by onflapp** [comment]
done.
Please feel free to structure it however you feel is appropriate.
Thanks for your help.

**Comment by zeroheure** [comment]
Thanks, but AFAIK it is not open for writing.

**Comment by onflapp** [comment]
I think the way github wiki pages supose to work is that you fork the repo, make your changes and then submit a push request.

**Comment by zeroheure** [comment]
Not at all AFAIK, because in other projects I can modify the Wiki freely.

**Comment by zeroheure** [comment]
See this documentation
https://docs.github.com/en/communities/documenting-your-project-with-wikis/changing-access-permissions-for-wikis

**Comment by onflapp** [comment]
OK, good to know.

give a try then. It should be open to anyone now.
Thanks

**Comment by zeroheure** [comment]
Yes it works !
