### ISSUE TITLE
WindowMaker: Workspace Focus Handling

### ISSUE THREAD

**Issue by Xylemon** [onflapp/gs-desktop#12]
I don't use GS-Desktop, but I use your WindowMaker fork, so I hope it's alright if I report this issue here.

The gist is that while focus handling has been fixed in a single workspace environment, if you use multiple workspaces such as myself, the bug is still very prevalent. To trigger the bug:

1) Have a GNUstep app open and focused in the current workspace
2) Switch workspaces while the app is focused
3) Now the menu for said app will linger on all workspaces, even not going away when selecting other GNUstep apps or any application in general

Any time spent on fixing this would be greatly appreciated.

I also want to thank you for taking the time to fix the many issues WindowMaker had with GNUstep apps, it was borderline unusable at times until your fork came along.

**Comment by onflapp** [comment]
Yes, I can confirm this problem. It is related to the way WindowMaker and GNUstep handles focus. It breaks other things as well. I am working on it ;-)

**Comment by onflapp** [comment]
> I don't use GS-Desktop, but I use your WindowMaker fork, so I hope it's alright if I report this issue here.
> 
> The gist is that while focus handling has been fixed in a single workspace environment, if you use multiple workspaces such as myself, the bug is still very prevalent. To trigger the bug:
> 
> 1. Have a GNUstep app open and focused in the current workspace
> 2. Switch workspaces while the app is focused
> 3. Now the menu for said app will linger on all workspaces, even not going away when selecting other GNUstep apps or any application in general
> 
> Any time spent on fixing this would be greatly appreciated.
> 
> I also want to thank you for taking the time to fix the many issues WindowMaker had with GNUstep apps, it was borderline unusable at times until your fork came along.

Please give it a try. It should be better now.

**Comment by Xylemon** [comment]
@onflapp you have done it again. If there is any way I can donate, please let me know.

Thank you again for your work. :)
