### ISSUE TITLE
Unable to run GNUstep apps installed via package manager

### ISSUE THREAD

**Issue by HUNT3Rdotme** [onflapp/gs-desktop#14]
Literally just heard about this project last night and wanted to contribute my own "thank you so much, however...."

Long story short -- using Debian as my reference point (I'm on unstable specifically, but I imagine this can also happen to anyone on stable or testing) -- I can't access any of the apps I installed via apt. So stuff like CharMap, Cynthiune, or Zipper I can't load without explicitly having it compiled/installed in (or symlinked to) `/Applications`.

**Comment by onflapp** [comment]
> Literally just heard about this project last night and wanted to contribute my own "thank you so much, however...."
> 
> Long story short -- using Debian as my reference point (I'm on unstable specifically, but I imagine this can also happen to anyone on stable or testing) -- I can't access any of the apps I installed via apt. So stuff like CharMap, Cynthiune, or Zipper I can't load without explicitly having it compiled/installed in (or symlinked to) `/Applications`.

This is expected.
GS-desktop compiles its own GNUstep libraries + many other dependencies that are needed to run it.
In fact, using any standard GNUstep-related Debian packages will most likely break GS-desktop.

**Comment by HUNT3Rdotme** [comment]
> This is expected.
> GS-desktop compiles its own GNUstep libraries + many other dependencies that are needed to run it.
> In fact, using any standard GNUstep-related Debian packages will most likely break GS-desktop.

In that case, is there any likelihood that GS-desktop might switch to more... "relative to package manager" sources for when the proper releases become a thing?

**Comment by onflapp** [comment]
> > This is expected.
> > GS-desktop compiles its own GNUstep libraries + many other dependencies that are needed to run it.
> > In fact, using any standard GNUstep-related Debian packages will most likely break GS-desktop.
> 
> In that case, is there any likelihood that GS-desktop might switch to more... "relative to package manager" sources for when the proper releases become a thing?

Absolutely, I just don't have the necessary knowledge nor time to do it. Source code distribution allows me to keep improving the GS-desktop without much overhead. It would be great if someone could help me to turn it into "live cd" type of distribution to make it accessible to wider public.

**Comment by HUNT3Rdotme** [comment]
Ah, that all tracks. In the meantime, dumb lil me didn't see all the extra applications available in this repo, but I digress somewhat.

Closing the issue now. Thank you!

**Comment by darkoverlordofdata** [comment]
I apologize if I’m butting in, but I’ve run into this issue on other projects. It's a bit political, and it’s very frustrating.

This started about a decade ago when ObjC 2.0 was released, and gcc declined to upgrade to support new extensions, so only clang will compile 2.x. Linux repo’s use gcc, so the last version of ObjC they can compile is 1.9.  

I’m currently using FreeBSD, where this is not a problem, as it uses clang, and the repository provides the ObjC 2.1 runtime, so all the applications are compiled with it. On the downside, FreeBSD has limited application availability and currently has no maintainer for GNUstep.

Possibly, a non-GNU linux with llvm toolchain, such as SerpentOS would also work. 

Or possibly someone can convince gcc to accept Apple's extensions, but I doubt that will happen.
