### ISSUE TITLE
Support for non-Debian platforms?

### ISSUE THREAD

**Issue by mbert** [onflapp/gs-desktop#15]
I understand that it's still very early and you probably work in a Debian environment. 
Nevertheless I'd just like to leave a message: I would really like to run gs-desktop on my Fedora box. I have started looking for the Debian dependencies' equaivalents, but my progress is extremely slow due to lack of time. 

Having packaged versions (both .deb and .rpm) in the end would be awesome.

**Comment by lproven** [comment]
> I would really like to run gs-desktop on my Fedora box.

Then I suggest you start by looking at NEXTSPACE:

https://github.com/trunkmaster/nextspace

It's a similar overall project, but built on top of CentOS Linux instead of Debian -- therefore probably much easier to adapt or get working.

**Comment by mbert** [comment]
Yes, I have NEXTSPACE in focus, too, but for well-known reason development is taking a big break.

**Comment by lproven** [comment]
Absolutely, yes. 

But ISTM that if the goal here is to have a NeXTstep-like environment, there are 2 paths:

* Adapt the existing one based on a now-dead RH-family OS
* Attempt to port a totally different Debian project.

I know which I'd rather attempt! :-)

I think there'd be a real public service in a version of NEXTSPACE on top of Fedora $CURRENT with a possible view to a future Fedora GNUstep spin.

**Comment by onflapp** [comment]
Although both NEXTSPACE and GS-desktop might look similar, each takes very different approach.  

GS-desktop is full source code distribution.  Therefore it should be absolutely possible to compile it on Fedora (or any other modern Linux distro).  You just have to make sure you have the right dependencies installed.  

I fully agree there should be list of dependencies for Fedora, but at the moment there is none as I use Debian myself.

**Comment by onflapp** [comment]
@mbert , there is now script for installing all Fedora dependencies.
I tested it on Fedora 38.
