### ISSUE TITLE
Sync some of the pull requests on main e.g NSDockTile

### ISSUE THREAD

**Issue by austintatiousness** [onflapp/gs-desktop#16]
Would you be able to pull in the changes to NSDockTile that were made on the main for libs-gui? I'm trying to exclusively use your build (especially because you seem to be very active in fixing bugs). I am trying to figure out some of the scaling issues with NSDockTile, but really don't want to switch out your version of libs-gui for the main one because I appreciate what you're doing and the changes you have made. If it would cause major conflicts, then no worries, I will make due and copy them in my local copy and build from there, until you can.

**Comment by onflapp** [comment]
done.
I merged both the gui and base forks
