### ISSUE TITLE
Some build problems on Fedora

### ISSUE THREAD

**Issue by mbert** [onflapp/gs-desktop#17]
Thank you for providing support for Fedora. A few issues I've run in, here's a diff to fix them. Should be pretty self-explaining.

[gs-desktop-fedora.zip](https://github.com/onflapp/gs-desktop/files/12475559/gs-desktop-fedora.zip)

Also: not sure whether this has been mentioned in the documentation: 
* When trying to compile gs-desktop on my system on which there's already some GNUStep software installed (e.g. through the package manager), the build of the WINGs GNUStep library fails with link errors
* After that aborted compile none of my installed GNUStep applications worked anymore, obviously caused by libraries installed by gs-desktop to /, so I had to move these directories out of the way - is there any way we can make gs-desktop coexist with existing installations? This is rather inconvenient...

**Comment by onflapp** [comment]
I incorporated your changes.
Many thanks!

GSDE includes some code changes that are not part of the main GNUstep branch (yet). Therefore it is not compatible with libraries or even configuration supplied by a distribution.  Any application will have to be recompiled to work with GSDE.

I agree this should be documented better.
