### ISSUE TITLE
Antialiased fonts.

### ISSUE THREAD

**Issue by paulodelgado** [onflapp/gs-desktop#19]
Not sure if this is by design but /System/etc/fonts.conf has

```
 <match target="font" >
    <edit mode="assign" name="antialias" >
      <bool>false</bool>
    </edit>
  </match>
```

In my install I changed that to `true` and also added one more `<dir>` entry for the default Debian fonts.  Now it looks like this:
```
<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">
<fontconfig>
  <dir>/System/Fonts</dir>
  <dir>/Library/Fonts</dir>
  <dir>/usr/share/fonts</dir>
.
.
.
```
I forked this repo because I wanted to submit a PR but figured I'd ask first to check this wasn't something set by design.

**Comment by onflapp** [comment]
Should be OK now. 
- the anti-aliasing is configured in the Preferences.app
- you can add additional fonts by copying them into ~/Library/Fonts or you can symlink the entire directory (e.g. ln -s /usr/share/fonts ~/Library/fonts)

**Comment by paulodelgado** [comment]
Thank you for replying.  I have two more questions, when you have some time.

`the anti-aliasing is configured in the Preferences.app` -> does this refer to the checkbox with "Enable LCD font smoothing" or am I missing something? I remember checking/unchecking this and nothing happened. 

I saw your new commits in this repo and want to pull those changes.  Is the best way to do so by running something like this:
```
su -
cd /path/to/gs-desktop
git pull
./fetch-world.sh
./build-world.sh
```
Or is there something I'm missing?

Thanks for the great work on this project!
