### ISSUE TITLE
Documentation on How to effectively  use GWorkspace 

### ISSUE THREAD

**Issue by cneira** [onflapp/gs-desktop#2]
It would be nice to have a tutorial or documentation on how to work with GWorkspace, sometimes I lose sight of it and need to execute it again. Also, I tried to change the wallpaper but saw no change in the background.

**Comment by onflapp** [comment]
The background is controlled by the WindowMaker.
- right click the desktop
- select info / preferences
- you can configure color or background images in the "Appearance Preferences"

**Comment by cneira** [comment]
Thanks! now is working.

**Comment by cneira** [comment]
This site has documentation on how the system works https://www.levenez.com/NeXTSTEP/Fonctions_CacheCache.html

**Comment by onflapp** [comment]
Please be aware that GNUstep Desktop is not clone of NeXTSTEP.
It looks similar in places but some things work very differently.

It is composed of many independent components.
For example: https://gnustep.github.io/experience/GWorkspace.html which is the file manager. 
And WindowMaker https://www.windowmaker.org which gives you the dock and window manager.

GNUstep Desktop tries to tie everything together using configuration and patching (if necessary).

**Comment by cneira** [comment]
Would be to hard to use https://github.com/trunkmaster/nextspace/tree/master/Applications/Workspace ? , I tried compiling nextspace kits and they build cleanly, but have not dig deeper into workspace.

**Comment by onflapp** [comment]
> Would be to hard to use https://github.com/trunkmaster/nextspace/tree/master/Applications/Workspace ? , I tried compiling nextspace kits and they build cleanly, but have not dig deeper into workspace.

GNUstep Desktop takes different approach. Rather than reimplementing NeXT applications from scratch as NEXTSPACE does, it uses existing projects to build complete desktop environment. The UI is going to be different but it has more functionality.

I suppose you could take NEXTSPACE to start with and then compile applications you want from GNUstep Desktop.
