### ISSUE TITLE
Unable to start GSDE

### ISSUE THREAD

**Issue by Mx-Iris** [onflapp/gs-desktop#25]
I tried Debian12 and Fedora39, neither of them can start GSDE with the following error

```
[root@fedora gs-desktop]# /System/bin/startgsde
xset:  unable to open display ""
[root@fedora gs-desktop]# 
```

**Comment by onflapp** [comment]
you will not be able to run GSDE as root.
Further more, GSDE needs to be started within X.
The easiest way to do so is to install default desktop (usually gnome) and then switch to the GSDE session in login panel.
