### ISSUE TITLE
Librarian

### ISSUE THREAD

**Issue by cneira** [onflapp/gs-desktop#3]
I tried to find information on how to use Librarian or how to add data to its index, I just could load the Unix Man pages available in the Documents folder, but I would like to add my own documents, is it possible?

**Comment by onflapp** [comment]
absolutely. The UNIX documentation is just an example.
- create new document
- open inspector
- add paths to index
- build the index

**Comment by cneira** [comment]
> absolutely. The UNIX documentation is just an example.
> 
> * create new document
> * open inspector
> * add paths to index
> * build the index

Great, thanks!, do I need to convert the documents to follow a specific format to be able to be picked up by Librarian/Helpeviewer ?

**Comment by onflapp** [comment]
> > absolutely. The UNIX documentation is just an example.
> > 
> > * create new document
> > * open inspector
> > * add paths to index
> > * build the index
> 
> Great, thanks!, do I need to convert the documents to follow a specific format to be able to be picked up by Librarian/Helpeviewer ?

Librarian uses recollindex command to index files in paths you specified. It is handles many different file types be default.
Please note that Librarian is only used for searching. The file itself will open in an app which is associated with given extension. For example PDF will open in DocViewer, whereas gsdoc will open in HelpViewer. 
You can support additional document types by creating filter/helper apps (see /Application/Utilities/Helpers). For example, markdown file would get converted into HTML and then opened by DocViewer or man page document gets converted into HelpViewer format.

**Comment by cneira** [comment]
Thanks! now is clear.
