### ISSUE TITLE
Add games such as Chess and Gomoku

### ISSUE THREAD

**Issue by coderamen666** [onflapp/gs-desktop#31]
Debian has a gnustep-games package and I enjoy it on my Raspberry Pi. It would be nice if you supported it in GSD (I don't use GSD yet)

**Comment by onflapp** [comment]
I added installation script to install additional games.
The scripts is in `gs-desktop/extra-apps` sub-directory.
You can launch the `Games.command` script from Workspace or in Terminal app. It will download necessary sources, build and install games into `/Application/Games` folder.
