### ISSUE TITLE
How can you update the system every few commits easily without rebuilding the whole thing?

### ISSUE THREAD

**Issue by coderamen666** [onflapp/gs-desktop#32]
I try to do this with mixed results. I tried to apply the new script for workspace and it didn't work. Also, the new service for the ScanImage app doesn't appear.

**Comment by onflapp** [comment]
This is not going to work. You need to build the whole desktop as there are many interdependencies. You might even have to clear you ~/Library from time to time as a lot of functionality is enabled via configuration.

**Comment by coderamen666** [comment]
Oof. Well, it will only take 30 minutes I guess.
