### ISSUE TITLE
Fix GWorkspace Menu

### ISSUE THREAD

**Issue by coderamen666** [onflapp/gs-desktop#34]
The GWorkspace menu is slowly moving up the screen after each reboot and I can move it off screen but it's an annoying process. It shifts up exactly 3 menu items of space, and I am pretty sure that it is a bug in steptalk. More specifically, in this function:

- (void)__restoreMenuFrames:(id) notification

https://github.com/onflapp/libs-steptalk/commit/7e44311876f7b5acd5a6ec190d2d8e7e5b62bf45#diff-7d06145d123dacf2643489ce5938d71150e2c79d4f417abfec8d847d32c74d5c

**Comment by onflapp** [comment]
did you build and install the entire GSDE, including clearing your ~/Library ?

**Comment by coderamen666** [comment]
Yes. This only started happening after multiple boots.

**Comment by onflapp** [comment]
I reverted the change. 
I need more time to debug it.

Thanks!
