### ISSUE TITLE
How to change modifier key

### ISSUE THREAD

**Issue by cneira** [onflapp/gs-desktop#37]
By default modifier key is Alt , is there an option to change this?.
I tried preferences.app modifiers menu but is not working.

**Comment by coderamen666** [comment]
Use the defaults command to change the modifier key.
https://gnustep.github.io/resources/documentation/User/Gui/KeyboardSetup.html

**Comment by cneira** [comment]
I tried that before using the example there but is not working. Do I need to restart windowmaker ?
