### ISSUE TITLE
GWorkspace Desktop is offset in the Y position

### ISSUE THREAD

**Issue by victorgabriel878** [onflapp/gs-desktop#38]
for some reason, GWorkspace's desktop is offset by 30 pixels (checked in gimp) up the screen

![github_issue_image](https://github.com/onflapp/gs-desktop/assets/72201555/254df78a-8d85-49dc-b0d2-d08bcbfe36d9)

you can see its offset, as the GWorkspace desktop wallpaper (darker blue) is visibly separate from the Window Maker wallpaper (lighter blue)

**Comment by victorgabriel878** [comment]
i've checked and it seems to be a problem with either Window Maker or the desktop environment, as i've tested the same code on another window manager and it worked fine.

**Comment by onflapp** [comment]
should work now (fixes to the wmaker)

**Comment by victorgabriel878** [comment]
thanks!
it worked, thanks for the help
