### ISSUE TITLE
Wrapper does not work

### ISSUE THREAD

**Issue by cneira** [onflapp/gs-desktop#4]
Currently, I'm trying to use WrapperFactory.app to create be to launch an application through openapp. 
Is there an example on how to use this tool to generate wrappers for applications?

**Comment by onflapp** [comment]
> Currently, I'm trying to use WrapperFactory.app to create be to launch an application through openapp.
> Is there an example on how to use this tool to generate wrappers for applications?

Helper app in /Application/Utilities/Helpers are all wrappers that call command line tool in the background.

- action
define what commands are execute per specific event. For example when application starts or is requested to open a file

- types
register types (file extensions) this application is able to open
You do not need to specify filter or return type, unless you want to implement filter service.
For example see DocHelper.app

- services
services appear in the "Services" menu and allow you to pass selection to a script (receives data as).
The script can also return data (returns data as).

**Comment by cneira** [comment]
Thanks, now it works!.
That info could be helpful on the help menu of the app
