### ISSUE TITLE
hints for how to use BUILD_SETTINGS.conf

### ISSUE THREAD

**Issue by mclarenlabs** [onflapp/gs-desktop#40]
I think the addition of BUILD_SETTINGS is a nice touch.  But it wasn't obvious why my build was failing with a gcc message.

I think a message in README.md about how to set it would be helpful.  For my system (debian12, clang14)  I simply did this

```
ln -s BUILD_SETTINGS.conf.clang BUILD_SETTINGS.conf
```
this is a minor nit.  It worked seamlessly after.

**Comment by onflapp** [comment]
I switched to GCC on purpose to enable debugging and to make it easier to build on *BSD. I don't test builds with clang anymore. But I agree with you that it should be documented better. 

What GCC errors where you getting?

**Comment by coderamen666** [comment]
It's really a shame because Clang adds a lot of new language features and brings the experience closer to MacOS.

**Comment by onflapp** [comment]
> It's really a shame because Clang adds a lot of new language features and brings the experience closer to MacOS.

I had to "back-port" Sound, Desktop and System kits to use gcc. It was a lot of effort. The upside is that I can finally use debugger and profiler and GSDE does not required latest and greatest Linux to compile anymore.

**Comment by mclarenlabs** [comment]
Just for your information,  the applications and libraries I am developing all need Clang with ARC, blocks and libdispatch.

I got a little tripped up with the latest build not creating libdispatch.  In 02-build_libdispatch.sh there was an "exit 0" line I needed to comment out.

```
#!/bin/sh

. ../BUILD_SETTINGS.conf
# exit 0
echo "=================="
echo " libdispatch"
echo "=================="

```

Once I commented out the "exit" the environment built fine.

The use of ../BUILD_SETTINGS.conf let me easily build a clang-based environment, like I need.

**Comment by onflapp** [comment]
fixed
Thanks!
