### ISSUE TITLE
gs-workspace: items can't be dragged to the Viewer window's shelf

### ISSUE THREAD

**Issue by levito** [onflapp/gs-desktop#41]
Dragging icons to the Viewer window's internal shelf doesn't work anymore. They will always show a "not allowed" mouse cursor. I'm not sure when this broke, but I remember it was working a couple of months ago. Dragging to the tabbed shelf on the desktop still works.

I'm using the most recent code from August 4, 2024 on Debian 12 and ran `install-dependencies-debian.sh`, `clean_world.sh`, `fetch_world.sh` and finally `build_world.sh` to install it.

**Comment by onflapp** [comment]
should be fixed now. Please give it a try.

**Comment by levito** [comment]
Yeah, it works again! Thanks a lot! This project is awesome, should have at least 9999 stars instead of 99 😉 

By the way: I'm currently using it along with SDDM, a couple of Qt apps, and the https://github.com/andbgr/QTStep theme along with Papirus icons in brown. Blends in really nicely!

I added PCManFm-Qt so I can for example reveal downloaded files from the browser. This doesn't work with the GWorkspace File Viewer since it's a very different beast. Do you think this is something that can be added?

The trash is another thing that works very differently between File Viewer and other file managers...

**Comment by onflapp** [comment]
I am experimenting with deeper integration of both Qt and GTK apps.
Look and feel is very doable but it is kind of tricky when it comes to key-shortcuts and drag & drop - but I’ll get there eventually ;-)
Integration with the browser should actually be quite easy. I just need to implement the right xdg standard and/or use DBUS (GSDE uses it already).

Is this Chrome or Firefox you are testing this with?

Thanks

**Comment by levito** [comment]
I have both installed so I could test this in both. Chromium is getting installed anyway since it's used by WebBrowser.app. The Firefox wrapper is nice since you made it use alt/option as command key, so it feels better integrated. I'm a bit torn which I like better. Chromium is more up to date in Debian, and it tends to work better with some websites. But I hate the shift to Manifest V3. Firefox keeps Manifest V2 for now, but on Debian, we only get the ESR from the official repos. This is missing some very desirable CSS features like the `:has()` selector.
