### ISSUE TITLE
Terminal.app -- can no longer change font

### ISSUE THREAD

**Issue by Jam1972** [onflapp/gs-desktop#42]
When attempting to apply the selected font, the "Set" button remains in the depressed state and freezes.

**Comment by onflapp** [comment]
is this happening with any font?
does this happen in the preferences -> window settings?
do you see any error in the desktop.log? (Console.app)

**Comment by Jam1972** [comment]
- Yes, any font.
- Correct, Preferences->Window settings. FWIW, the issue is also present if I access the dialog from the Font->Font Panel.
- Nothing in the desktop.log.

![font-panel](https://github.com/user-attachments/assets/dbc9e4eb-04d0-458b-bc29-38969b6a03a5)

**Comment by Jam1972** [comment]
So, I've noticed these exceptions when I open the Preferences->Windows dialog:

...except: 2e00050 Terminal
...except: 2e00512 Terminal
...except: 2e00050 Terminal
...except: 2e00512 Terminal

**Comment by onflapp** [comment]
no, those are not exceptions. These are debugging log entries from the window manager handling the focus.
Could you clear the log (e.g. echo "" > $GS_DESKTOP_LOG)
Trigger the error and send me content of the $GS_DESKTOP_LOG please?

**Comment by Jam1972** [comment]
Here you go:
[log.zip](https://github.com/user-attachments/files/16677392/log.zip)

**Comment by Jam1972** [comment]
The relevant entry seems to be this one:
2024-08-20 16:34:08.916 Terminal[1476777:1476777] DPS
(xgps): no font set

**Comment by Jam1972** [comment]
FWIW, I can set/change the font without issues on other "terminal"-based apps such as the Console

**Comment by onflapp** [comment]
hmm, did you install all dependencies? 
To me this looks like the terminal is using old Xlib backend. 
Make sure you have libart library installed. Or maybe there was compile/configure issue in gnustep-backend.

**Comment by Jam1972** [comment]
Manually installing libart and recompiling world fixed it.
Thanks and sorry for the wasted time.
