### ISSUE TITLE
GSWebBrowser does not  open popups windows

### ISSUE THREAD

**Issue by cneira** [onflapp/gs-desktop#5]
Trying meet.jitsi.si    I don't see the popups to allow permission to use microphone and camera, so  I'm not able to join a meeting using GSWebBrowser

**Comment by onflapp** [comment]
> Trying meet.jitsi.si I don't see the popups to allow permission to use microphone and camera, so I'm not able to join a meeting using GSWebBrowser

Please give it try now. I enabled necessary permissions in the manifest file.

**Comment by cneira** [comment]
Thanks! is working now.
