### ISSUE TITLE
StepTalk documentation

### ISSUE THREAD

**Issue by cneira** [onflapp/gs-desktop#6]
I was trying to find information about StepTalk for scripting but I keep getting 404 on the resources I found.
Is it possible to use scripting to call and app with a predefined command?

For example instead of executing Screen Shot.app from the dock I want to use alt+shift+4  to take a screenshot of a screen section using the screenshot app, is that possible?

**Comment by cneira** [comment]
This is awesome!, it was really simple, I created a file called takeone.st
`
ScreenShot takeScreenShot:nil
`
then just call it with  
`
stexec takeone.st
`

**Comment by onflapp** [comment]
Yes, StepTalk is awesome!
Unfortunately the official project has been abandoned for years.
The only really documentation is documentation and examples that come with the source code.
 BTW: if you want to launch a script using global short cut:
-  right click the desktop
- info -> preferences
- application menu
- add "run external command" to your menu
- associate it with a key shortcut
