### ISSUE TITLE
GSWebbrowser does not respect copy/paste keys

### ISSUE THREAD

**Issue by cneira** [onflapp/gs-desktop#7]
In all GNUStep apps I'm using #c #v to copy and paste but trying the same in GSWebbrowser does not work, I cannot copy from GNUStep apps to   the webview of the browser or from  the page contents from the browser to GNUStep apps.

**Comment by onflapp** [comment]
In short, this *should* work (and does for me as I am trying right now). It must be a bug.
It is keyboard shortcuts you have problem with / selecting copy & paste from menu works or do you have copy & paste problem in general. 
Please note that only text is expect to work. If you try to copy and paste anything else, there might be a problem.

**Comment by onflapp** [comment]
OK -- I see, I guess you are using alt as your command modifier.
Yes, this is a bug.

**Comment by onflapp** [comment]
> In all GNUStep apps I'm using #c #v to copy and paste but trying the same in GSWebbrowser does not work, I cannot copy from GNUStep apps to the webview of the browser or from the page contents from the browser to GNUStep apps.

should be OK now

**Comment by cneira** [comment]
awesome!, works perfect thanks a lot!.
