### ISSUE TITLE
Nextspace gnustep-back vs currently used in gs-desktop

### ISSUE THREAD

**Issue by cneira** [onflapp/gs-desktop#8]
I just tried nextspace gnustep-back and focus handling worked a lot better, menus are not cluttered when multiple applications are open, seems it was part of @trunkmaster changes, he writes about this here: 
https://trunkmaster.github.io/

I checked your version of gnustep-base and you also have done some changes in there, maybe would be nice to merge both branches ?

**Comment by onflapp** [comment]
This has been fixed in GS Desktop's fork of WindowMaker.
Or do you refer to some other problem?

**Comment by cneira** [comment]
What I noticed if you run several applications their menus will clutter up, when using the nextspace-back lib the only menus that will appear in the screen are the ones of the active application,  maybe I'm confused.

**Comment by onflapp** [comment]
> What I noticed if you run several applications their menus will clutter up, when using the nextspace-back lib the only menus that will appear in the screen are the ones of the active application, maybe I'm confused.

That's exactly how the WindowMaker fork should work.
Do you use the /System/bin/startgsde script? 
Hopefully there is no other version of WindowMaker being picked up.

**Comment by cneira** [comment]
I'm sorry  I meant nextspace-gnustep-back, I tried to use nextspace-gnuspace-gui as well but does not compiles.

**Comment by onflapp** [comment]
gs-desktop uses gs-window maker to handle focus. Nextspace is using different approach, therefore libraries are not really interchangeable.
