### ISSUE TITLE
GSWebbrowser downloads are not working

### ISSUE THREAD

**Issue by cneira** [onflapp/gs-desktop#9]
Trying to download this file https://freesound.org/people/theplax/sounds/624923/

the download popup appears but the file is lost, as is not saved  on the requested folder.

Have you checked surf browser? is just a wrapper to webkit maybe that's ligther to use chromium I'm in a 2gb system and gs-desktop works great, the only high memory consumer is chrome.

**Comment by onflapp** [comment]
The download doesn't work yet.

I did experiment with using gtkwebkit with GNUstep. It works very well. However, WebBrowser.app is specifically intended to work with Chrome.

**Comment by onflapp** [comment]
> Trying to download this file https://freesound.org/people/theplax/sounds/624923/
> 
> the download popup appears but the file is lost, as is not saved on the requested folder.
> 

The download works now. 
URLs that are protected by authentication/cookie might not work yet.

**Comment by HaroleDev** [comment]
I'm on Debian 11 arm64, yet the WebBrowser.app doesn't work, even installing the chromium package.

**Comment by onflapp** [comment]
> I'm on Debian 11 arm64, yet the WebBrowser.app doesn't work, even installing the chromium package.

what problem do you have?

**Comment by HaroleDev** [comment]
Oh nevermind, it works now. Just had to shutdown and boot up again.
![Screenshot 2023-06-05 at 22 23 39](https://github.com/onflapp/gs-desktop/assets/47141290/191dcb8c-59c3-45af-9532-5dce45d86dcd)
